spring:
  profiles: default

  datasource:
    url: jdbc:mysql://localhost:13309/bookstore?useSSL=false&allowPublicKeyRetrieval=true&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: rootpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    hibernate.ddl-auto: update

  # flyway multiple 시, java based 고려.
  flyway:
    enabled: true
    encoding: UTF-8
    url: jdbc:mysql://localhost:13309/bookstore
    user: root
    password: rootpass
    sql-migration-prefix: V
    sql-migration-suffixes: .sql
    sql-migration-separator: __
    locations: classpath:db/migration,classpath:db/callback